server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#         uri: file:///Users/yoonheesang/Documents/my-spring-cloud-config-1
          uri: https://github.com/hsyoon900528/my-spring-cloud-config.git
#          username: edowon0623@gmail.com
#          password: [password]

management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh, refresh, metrics
